
# This file represents the configuration for the Supabase Project

[env.secrets]
# Supabase specific keys
SUPABASE_URL = "https://wyazzjcyjyxirjsplaps.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5YXp6amN5anl4aXJqc3BsYXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODQ2NDQsImV4cCI6MjA2MTQ2MDY0NH0.EDer1qy3QLQrTdjjHhEdByLmbliDtlj1iiXxkizrkIk"
PAYMENT_API_KEY = "sk_MiPcpHOVy02JdXmEUN8OWq-bQNbn4u_D09lNNfA8LX0Q-Vo_"
PAYMENT_PUBLIC_KEY = "pk_cxB1fS-bnOsQr8c2NIiwN61astAjC4IBJJ4bBEvrQH0nDL5G"

[project]
id = "wyazzjcyjyxirjsplaps"
