// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyazzjcyjyxirjsplaps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5YXp6amN5anl4aXJqc3BsYXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODQ2NDQsImV4cCI6MjA2MTQ2MDY0NH0.EDer1qy3QLQrTdjjHhEdByLmbliDtlj1iiXxkizrkIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);